"""Provenance header lines stamped into every generated file.

Each output file records *when* it was generated and *which version of this
tool* generated it (the git commit of the UTKBudgetExtractor checkout, plus a
note when that checkout has uncommitted changes), so a generated ``.tex`` file
can always be traced back to the code that produced it.
"""

from __future__ import annotations

import functools
import os
import subprocess
from datetime import datetime
from typing import List, Optional, Tuple

# Repository root = parent of the directory containing this file.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@functools.lru_cache(maxsize=1)
def git_revision(repo: str = _REPO_ROOT) -> Tuple[Optional[str], bool]:
    """Return ``(commit_hash, dirty)`` for ``repo``.

    ``commit_hash`` is ``None`` when ``repo`` is not a git checkout or git is
    unavailable.  ``dirty`` is ``True`` when the working tree has uncommitted
    changes (tracked modifications or untracked, non-ignored files).
    """
    def _git(*args: str) -> Optional[str]:
        try:
            out = subprocess.check_output(
                ["git", "-C", repo, *args],
                stderr=subprocess.DEVNULL,
            )
            return out.decode("utf-8", "replace").strip()
        except (subprocess.CalledProcessError, FileNotFoundError, OSError):
            return None

    commit = _git("rev-parse", "HEAD")
    if commit is None:
        return None, False
    status = _git("status", "--porcelain")
    dirty = bool(status)  # non-empty -> uncommitted changes
    return commit, dirty


def provenance_lines() -> List[str]:
    """Comment bodies (without the leading ``% ``) for a file header."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    try:
        from . import __version__ as version
    except Exception:  # pragma: no cover - defensive
        version = "?"

    lines = [f"Auto-generated by UTKBudgetExtractor v{version} on {timestamp}"]

    commit, dirty = git_revision()
    if commit:
        note = " (UNCOMMITTED CHANGES PRESENT)" if dirty else ""
        lines.append(f"Generator commit: {commit}{note}")
    else:
        lines.append("Generator commit: unknown (not a git checkout)")
    return lines


def provenance_comment(extra: Optional[List[str]] = None) -> str:
    """Return the provenance lines as a block of LaTeX (``%``) comments."""
    lines = provenance_lines()
    if extra:
        lines.extend(extra)
    return "\n".join(f"% {line}" for line in lines)
